# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fffd161bb9caf526e225a5a6e38121c7"
name = "Stackly Subscriptions"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_products,write_purchase_options"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
